name: build and upload to S3

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet latest v6.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'
      - name: Display dotnet version
        run: dotnet --version
      - name: publish dotnet project to publish folder
        run: dotnet publish -o ./publish
      - name: create a zip of publish folder
        run: zip -r deploy_app.zip publish
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: aws s3 sync --delete ./deploy_app.zip ${{ secrets.AWS_S3_URI }}